/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sadeem
 */
public class availableFlights extends javax.swing.JFrame {
   final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";

     PreparedStatement ps=null;
      ResultSet rs=null;
    static Connection connection = null;
 static String FlightNo=null;
 String FlightPrice=null;
String Depdate=null;
String Arridate=null;
String Deptime=null;
String Arritime=null;
String Depcity=null;
String Arricity=null;
String classt=null;
static int noOfTickets;


    /**
     * Creates new form availableFlights
     */
    public availableFlights() {
        initComponents();
        avFlights();
        tableH();
        
    }
    public void tableH(){
        JTableHeader th=flightsTb.getTableHeader();
        th.setForeground(Color.BLUE);
        th.setFont(new Font("Times New Roman",Font.BOLD,14));
        TableColumn tc1=flightsTb.getColumnModel().getColumn(0);
        tc1.setPreferredWidth(100);
         TableColumn tc2=flightsTb.getColumnModel().getColumn(1);
        tc2.setPreferredWidth(100);
         TableColumn tc3=flightsTb.getColumnModel().getColumn(2);
        tc3.setPreferredWidth(100);
         TableColumn tc4=flightsTb.getColumnModel().getColumn(3);
        tc4.setPreferredWidth(120);
         TableColumn tc5=flightsTb.getColumnModel().getColumn(4);
        tc5.setPreferredWidth(120);
         TableColumn tc6=flightsTb.getColumnModel().getColumn(5);
        tc6.setPreferredWidth(100);
         TableColumn tc7=flightsTb.getColumnModel().getColumn(6);
        tc7.setPreferredWidth(100);
         TableColumn tc8=flightsTb.getColumnModel().getColumn(7);
        tc8.setPreferredWidth(100);
         TableColumn tc9=flightsTb.getColumnModel().getColumn(8);
        tc9.setPreferredWidth(100);
        
        
    }
    public void avFlights(){
        
         try {
             int rowC=0;
            connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
             ps = connection.prepareStatement("SELECT * FROM FLIGHT WHERE DEPARTURE_CITY =? AND ARRIVAL_CITY =?");
               ps.setString(1, SearchingFlightsInterface.depcity);
            ps.setString(2, SearchingFlightsInterface.arricity);
            rs=ps.executeQuery();
           while(rs.next()){
               
            FlightNo = String.valueOf(rs.getInt("FLIGHT_NO"));
           FlightPrice=String.valueOf(rs.getDouble("FLIGHT_PRICE"));
           Depdate=rs.getString("DEP_DATE");
           Deptime=rs.getString("DEP_TIME");
           Arridate=rs.getString("ARR_DATE");
           Arritime=rs.getString("ARR_TIME");
             Depcity=rs.getString("DEPARTURE_CITY");
              Arricity= rs.getString("ARRIVAL_CITY");    
           classt=rs.getString("CLASS");   
             String data[]={FlightNo,Depdate,Deptime,Arridate,Arritime,Depcity,Arricity,classt,FlightPrice};
             DefaultTableModel tbM=(DefaultTableModel)flightsTb.getModel();
        tbM.insertRow(rowC, data);

           }
         
         }
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
 public void closeDB(){
        try{
        rs.close();
        ps.close();
        connection.close();}
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightsTb = new javax.swing.JTable();
        searchingL = new javax.swing.JLabel();
        nooftcktsCB = new javax.swing.JComboBox<>();
        searchingL1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cancelB = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVAILABLE FLIGHTS");

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flightsTb.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        flightsTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        flightsTb.setForeground(new java.awt.Color(0, 0, 51));
        flightsTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FLIGHT NO", "DEP DATE", "DEP TIME", "ARRIVAL DATE", "ARRIVAL TIME", "FROM", "TO", "CLASS", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flightsTb.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        flightsTb.setGridColor(new java.awt.Color(0, 0, 102));
        flightsTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightsTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flightsTb);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 950, 120));

        searchingL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        searchingL.setForeground(new java.awt.Color(0, 0, 102));
        searchingL.setText("AVAILABLE FLIGHTS");
        jPanel2.add(searchingL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 30));

        nooftcktsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel2.add(nooftcktsCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 20));

        searchingL1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchingL1.setForeground(new java.awt.Color(0, 0, 102));
        searchingL1.setText("NO OF TICKETS :");
        jPanel2.add(searchingL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/logo.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cancelB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });
        jPanel2.add(cancelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        background1.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/backgroundBig.jpg")); // NOI18N
        jPanel2.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flightsTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsTbMouseClicked
try{

        // TODO add your handling code here:
        int i=flightsTb.getSelectedRow();
        TableModel fmodel=flightsTb.getModel();
      if( fmodel.getValueAt(i, 0) !=null){
          FlightNo = fmodel.getValueAt(i, 0).toString();
           FlightPrice=fmodel.getValueAt(i, 8).toString();
           Depdate=fmodel.getValueAt(i, 1).toString();
           Deptime=fmodel.getValueAt(i, 2).toString();
           Arridate=fmodel.getValueAt(i, 3).toString();
           Arritime=fmodel.getValueAt(i, 4).toString();
             Depcity=fmodel.getValueAt(i, 5).toString();
              Arricity= fmodel.getValueAt(i, 6).toString();
           classt=fmodel.getValueAt(i, 7).toString();
             noOfTickets=Integer.parseInt(nooftcktsCB.getItemAt(nooftcktsCB.getSelectedIndex()));
      }
                     connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
             ps = connection.prepareStatement("SELECT * FROM TICKET WHERE FILGHT_NO =? AND PASSENGER_ID =?");
               ps.setString(1, FlightNo);
            ps.setInt(2,PassengerMenu.ID);
            rs=ps.executeQuery();
            
            if(!rs.next()){
        
          String mess="Are You Sure Proceed with Flight NO is "+ FlightNo +" AND No Of Ticket is "+noOfTickets;
        String con="Confirming Your Booking From "+Depcity+" To "+Arricity;
     
                   int ch= JOptionPane.showConfirmDialog(this, mess , con,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                     //yes
                     if(ch==0){
                         bookingCon c=new bookingCon();
                         c.setVisible(true);
                         dispose();
                         closeDB();
                      } 
                     //no
                     else
                          if(ch==1){
                              PassengerMenu p=new PassengerMenu();
                              p.setVisible(true);
                              dispose();
                              closeDB();
                              
                          }
      
      else {
     JOptionPane.showMessageDialog(null, "Please Select a Valid Selection !", "Error", ERROR_MESSAGE);

      }}else
 JOptionPane.showMessageDialog(null, "You Have Reserved This Ticket Already", "Error", ERROR_MESSAGE);
   
            
            
            }
       catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    
       
    }//GEN-LAST:event_flightsTbMouseClicked

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        PassengerMenu m=new PassengerMenu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(availableFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(availableFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(availableFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(availableFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new availableFlights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JButton cancelB;
    private javax.swing.JTable flightsTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nooftcktsCB;
    private javax.swing.JLabel searchingL;
    private javax.swing.JLabel searchingL1;
    // End of variables declaration//GEN-END:variables
}
