/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sadeem
 */
public class Cancelinterface extends javax.swing.JFrame {
final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
    final String SELECT_QUERY = "SELECT * FROM PASSENGER";
    static Connection connection = null;
     PreparedStatement ps=null;
      ResultSet  rs=null;
      int IdNum=PassengerMenu.ID;
      int ticketN;
       static String selectedTicket;
    /**
     * Creates new form Cancelinterface
     */
    public Cancelinterface() {
        initComponents();
        setTickets();
    }
        
public void setTickets(){
      try{  connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");

  ps = connection.prepareStatement("SELECT * FROM TICKET WHERE PASSENGER_ID =?");
           
             ps.setString(1, String.valueOf(IdNum));
             
                    rs = ps.executeQuery();
         
                  while(rs.next()){
               
               ticketN=rs.getInt("TICKET_NO");
               reservedTickets.addItem(String.valueOf(ticketN));
                            
                      
              
                  }
                    ps.close();
                  connection.close();
                
            


    }
    catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regestrationL = new javax.swing.JLabel();
        cancelBt = new javax.swing.JButton();
        reservedTickets = new javax.swing.JComboBox<>();
        regestrationL1 = new javax.swing.JLabel();
        viewB = new javax.swing.JButton();
        regestrationL2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regestrationL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        regestrationL.setForeground(new java.awt.Color(0, 0, 102));
        regestrationL.setText("Cancel My Ticket");
        jPanel1.add(regestrationL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        cancelBt.setBackground(new java.awt.Color(255, 255, 255));
        cancelBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelBt.setForeground(new java.awt.Color(0, 0, 102));
        cancelBt.setText("Back");
        cancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, -1));

        reservedTickets.setSelectedIndex(-1);
        reservedTickets.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reservedTicketsItemStateChanged(evt);
            }
        });
        jPanel1.add(reservedTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 110, -1));

        regestrationL1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        regestrationL1.setForeground(new java.awt.Color(0, 0, 102));
        regestrationL1.setText("Choose The Ticket You'd Like To Cancel");
        jPanel1.add(regestrationL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 290, -1));

        viewB.setBackground(new java.awt.Color(255, 255, 255));
        viewB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewB.setForeground(new java.awt.Color(0, 0, 102));
        viewB.setText("Submit");
        viewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBActionPerformed(evt);
            }
        });
        jPanel1.add(viewB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        regestrationL2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        regestrationL2.setForeground(new java.awt.Color(0, 0, 102));
        regestrationL2.setText("Ticket No");
        jPanel1.add(regestrationL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, -1));

        background.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/background1.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtActionPerformed
        // TODO add your handling code here:
        PassengerMenu p=   new PassengerMenu();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelBtActionPerformed

    private void reservedTicketsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reservedTicketsItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_reservedTicketsItemStateChanged

    private void viewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBActionPerformed
        selectedTicket=reservedTickets.getSelectedItem().toString();
        SelectedTicketCancel c=new SelectedTicketCancel();
        c.setVisible(true);// TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_viewBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancelinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancelinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancelinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancelinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancelinterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelBt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel regestrationL;
    private javax.swing.JLabel regestrationL1;
    private javax.swing.JLabel regestrationL2;
    private javax.swing.JComboBox<String> reservedTickets;
    private javax.swing.JButton viewB;
    // End of variables declaration//GEN-END:variables
}
