/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sadeem
 */
public class deleting extends javax.swing.JFrame {
    final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
   
Connection connection=null;
            PreparedStatement ps1=null;
            
             PreparedStatement ps2=null;
             
              PreparedStatement ps3=null;
            ResultSet rs1=null;
            String flightNo;
    /**
     * Creates new form deleting
     */
    public deleting() {
        initComponents();
        fill();
    }
public void fill(){
  try{
                connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
               ps1 = connection.prepareStatement("SELECT distinct FLIGHT_NO FROM Flight");
   
            rs1= ps1.executeQuery();
        
          while (rs1.next()){
             
             combo.addItem(String.valueOf(rs1.getInt("FLIGHT_NO")));
            }
       }
      
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
   
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try{
       
       flightNo=combo.getSelectedItem().toString();
    connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
    ps1=connection.prepareStatement("SELECT *FROM TICKET WHERE FILGHT_NO=?");
     ps1.setString(1,flightNo);
     rs1=ps1.executeQuery();
     if(rs1.next()){
            ps2=connection.prepareStatement("DELETE FROM TICKET WHERE FILGHT_NO=?");
    
    
    ps2.setString(1,flightNo);
   int x= ps2.executeUpdate();
   
     }
    
 
     ps3=connection.prepareStatement("DELETE FROM FLIGHT WHERE FLIGHT_NO=?");
    ps3.setString(1,flightNo);
    int y= ps3.executeUpdate();
        fill();
    if(y>0){
            JOptionPane.showMessageDialog(null, "thanks !");
        
    }
    
    else
        JOptionPane.showMessageDialog(null, "failed !");
    
   
   }
   
   
   
    catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
   
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
