/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author sadeem
 */
public class editinfo extends javax.swing.JFrame {
     final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
 
    static Connection connection = null;
     PreparedStatement ps=null;
      ResultSet  rs=null;
    String username1=null;
   String password=null;
                String fname=null;
                String lname=null;
                String email=null;
                String phone=null;
                String gender=null;
    /**
     * Creates new form editinfo
     */
    public editinfo() {
        initComponents();
        setData();
     
        
        
    }

      public void setData(){
        
        try{
                        connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");

                ps = connection.prepareStatement("SELECT * FROM PASSENGER WHERE USERNAME =?");
           
             ps.setString(1,PassengerMenu.username);
                    rs = ps.executeQuery();
         
                  if(rs.next()){
                          username1=rs.getString("USERNAME");
                      usernameTx.setText(username1);
                     password=rs.getString("PASSWORD");
                     passwordTx.setText(password);
                     fname=rs.getString("FNAME");
                     firstnameTx.setText(fname);
              lname=rs.getString("LNAME");
lastnameTx.setText(lname);
 phone=rs.getString("PHONE_NUM");
 phoneTx.setText(phone);

                            
                      
              
                  }

    }
    catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
      public void updateData(){
          try{ 
          ps = connection.prepareStatement("UPDATE PASSENGER SET USERNAME=?,PASSWORD=?,FNAME=?,"
                  + "LNAME=?,PHONE_NUM=?"
                  + "WHERE USERNAME =?");
           username1= usernameTx.getText();
           password=String.valueOf(passwordTx.getPassword());
fname=firstnameTx.getText();
lname=lastnameTx.getText();
phone=phoneTx.getText();
             ps.setString(1,username1);
              ps.setString(2,password);
               ps.setString(3,fname);
                ps.setString(4,lname);
                 ps.setString(5,phone);
                   ps.setString(6,PassengerMenu.username);
              int upRow=  ps.executeUpdate();
              setData();
          if(upRow>0){
      JOptionPane.showMessageDialog(null, "You Have Successfully Updated Your Info ! Thank You ");
PassengerMenu pm=new PassengerMenu();
pm.setVisible(true);
dispose();

closeDB();


          }
          else {
                                    JOptionPane.showMessageDialog(null, "Error ocured", "Error", ERROR_MESSAGE);
                                }
          
         
          
          }
           catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
         
          
          
          
          
          
      }
public void closeDB(){
    try{
        rs.close();
        ps.close();
        connection.close();
    }
    catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regestrationL = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        firstnameL = new javax.swing.JLabel();
        lastnameL = new javax.swing.JLabel();
        phoneNoL = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        firstnameTx = new javax.swing.JTextField();
        lastnameTx = new javax.swing.JTextField();
        codeL = new javax.swing.JLabel();
        phoneTx = new javax.swing.JTextField();
        usernameTx = new javax.swing.JTextField();
        cancelBt = new javax.swing.JButton();
        updateBt = new javax.swing.JButton();
        passwordTx = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regestrationL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        regestrationL.setForeground(new java.awt.Color(0, 0, 102));
        regestrationL.setText("Edit My Information");
        jPanel1.add(regestrationL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        passwordL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwordL.setForeground(new java.awt.Color(0, 0, 102));
        passwordL.setText("Password :");
        jPanel1.add(passwordL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, 30));

        firstnameL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firstnameL.setForeground(new java.awt.Color(0, 0, 102));
        firstnameL.setText("First Name :");
        jPanel1.add(firstnameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        lastnameL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lastnameL.setForeground(new java.awt.Color(0, 0, 102));
        lastnameL.setText("Last Name :");
        jPanel1.add(lastnameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        phoneNoL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoneNoL.setForeground(new java.awt.Color(0, 0, 102));
        phoneNoL.setText("Phone No :");
        jPanel1.add(phoneNoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        usernameL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameL.setForeground(new java.awt.Color(0, 0, 102));
        usernameL.setText("UserName :");
        jPanel1.add(usernameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 20));

        firstnameTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxActionPerformed(evt);
            }
        });
        jPanel1.add(firstnameTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 120, 20));

        lastnameTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTxActionPerformed(evt);
            }
        });
        jPanel1.add(lastnameTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 20));

        codeL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        codeL.setForeground(new java.awt.Color(0, 0, 102));
        codeL.setText("+966");
        jPanel1.add(codeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        phoneTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxActionPerformed(evt);
            }
        });
        jPanel1.add(phoneTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 120, 20));

        usernameTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 20));

        cancelBt.setBackground(new java.awt.Color(255, 255, 255));
        cancelBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancelBt.setForeground(new java.awt.Color(0, 0, 102));
        cancelBt.setText("Cancel");
        cancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        updateBt.setBackground(new java.awt.Color(255, 255, 255));
        updateBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updateBt.setForeground(new java.awt.Color(0, 0, 102));
        updateBt.setText("Update");
        updateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtActionPerformed(evt);
            }
        });
        jPanel1.add(updateBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        passwordTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxActionPerformed(evt);
            }
        });
        jPanel1.add(passwordTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/background1.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxActionPerformed

    private void lastnameTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTxActionPerformed

    private void phoneTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxActionPerformed

    private void usernameTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxActionPerformed

    private void cancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtActionPerformed
        // TODO add your handling code here:
        if(rs!=null&&ps!=null&connection!=null){
            closeDB();
        }
        PassengerMenu p=   new PassengerMenu();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelBtActionPerformed

    private void updateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtActionPerformed
updateData();
        // TODO add your handling code here:


    }//GEN-LAST:event_updateBtActionPerformed

    private void passwordTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelBt;
    private javax.swing.JLabel codeL;
    private javax.swing.JLabel firstnameL;
    private javax.swing.JTextField firstnameTx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastnameL;
    private javax.swing.JTextField lastnameTx;
    private javax.swing.JLabel passwordL;
    private javax.swing.JPasswordField passwordTx;
    private javax.swing.JLabel phoneNoL;
    private javax.swing.JTextField phoneTx;
    private javax.swing.JLabel regestrationL;
    private javax.swing.JButton updateBt;
    private javax.swing.JLabel usernameL;
    private javax.swing.JTextField usernameTx;
    // End of variables declaration//GEN-END:variables
}
