/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author sadeem
 */
public class PassengerLoginForm extends javax.swing.JFrame {

    /**
     * Creates new form PassengerLoginForm
     */
    public PassengerLoginForm() {
        initComponents();
        
    }
    final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
    final String SELECT_QUERY = "SELECT * FROM PASSENGER";
    static Connection connection = null;
 PreparedStatement ps=null;
     ResultSet rs=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        regestrationL3 = new javax.swing.JLabel();
        passwordL3 = new javax.swing.JLabel();
        usernameL3 = new javax.swing.JLabel();
        usernameTx = new javax.swing.JTextField();
        signupBt = new javax.swing.JButton();
        loginBt = new javax.swing.JButton();
        passwordTx = new javax.swing.JPasswordField();
        passwordL4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signupBt1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regestrationL3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        regestrationL3.setForeground(new java.awt.Color(0, 0, 102));
        regestrationL3.setText("SIGN IN");
        jPanel4.add(regestrationL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        passwordL3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        passwordL3.setForeground(new java.awt.Color(0, 0, 102));
        passwordL3.setText("Don't Have an Account ?");
        jPanel4.add(passwordL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, 30));

        usernameL3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameL3.setForeground(new java.awt.Color(0, 0, 102));
        usernameL3.setText("UserName :");
        jPanel4.add(usernameL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 20));

        usernameTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxActionPerformed(evt);
            }
        });
        jPanel4.add(usernameTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, 20));

        signupBt.setBackground(new java.awt.Color(255, 255, 255));
        signupBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        signupBt.setForeground(new java.awt.Color(0, 0, 102));
        signupBt.setText("Sign Up");
        signupBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtActionPerformed(evt);
            }
        });
        jPanel4.add(signupBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        loginBt.setBackground(new java.awt.Color(255, 255, 255));
        loginBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loginBt.setForeground(new java.awt.Color(0, 0, 102));
        loginBt.setText("Login");
        loginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtActionPerformed(evt);
            }
        });
        jPanel4.add(loginBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 90, 30));

        passwordTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxActionPerformed(evt);
            }
        });
        jPanel4.add(passwordTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 120, -1));

        passwordL4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwordL4.setForeground(new java.awt.Color(0, 0, 102));
        passwordL4.setText("Password :");
        jPanel4.add(passwordL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/login.png")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        signupBt1.setBackground(new java.awt.Color(255, 255, 255));
        signupBt1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        signupBt1.setForeground(new java.awt.Color(0, 0, 102));
        signupBt1.setText("Main Menu");
        signupBt1.setBorder(null);
        signupBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBt1ActionPerformed(evt);
            }
        });
        jPanel4.add(signupBt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/background1.jpg")); // NOI18N
        jPanel4.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxActionPerformed

    private void signupBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtActionPerformed
        // TODO add your handling code here:
         passengerinterface p=   new passengerinterface();
     p.setVisible(true);
         dispose();

         
    }//GEN-LAST:event_signupBtActionPerformed

    private void loginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtActionPerformed
        // TODO add your handling code here:
   try {
            connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
             ps = connection.prepareStatement("SELECT * FROM PASSENGER WHERE USERNAME =? AND PASSWORD =?");
        
                String username= usernameTx.getText();
            String password = String.valueOf(passwordTx.getPassword());
           
            ps.setString(1, username);
            ps.setString(2, password);
       rs = ps.executeQuery();
     
        if (rs.next()) {
            
              PassengerMenu.username=username;
                
                  PassengerMenu p=   new PassengerMenu();
        p.setVisible(true);
      dispose();
      closeDB();
        
           } else {
              JOptionPane.showMessageDialog(null, "Username/Password is wrong!", "Error", ERROR_MESSAGE);
           }

             
   
   }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
   

    }//GEN-LAST:event_loginBtActionPerformed

    private void passwordTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxActionPerformed

    private void signupBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBt1ActionPerformed
        // TODO add your handling code here:
        Welcoming2 w=new Welcoming2();
        w.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_signupBt1ActionPerformed

    public void closeDB(){
        try{
        rs.close();
        ps.close();
        connection.close();}
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginBt;
    private javax.swing.JLabel passwordL3;
    private javax.swing.JLabel passwordL4;
    private javax.swing.JPasswordField passwordTx;
    private javax.swing.JLabel regestrationL3;
    private javax.swing.JButton signupBt;
    private javax.swing.JButton signupBt1;
    private javax.swing.JLabel usernameL3;
    private javax.swing.JTextField usernameTx;
    // End of variables declaration//GEN-END:variables
}
