/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sadeem
 */
public class PassengerMenu extends javax.swing.JFrame {
 final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
    final String SELECT_QUERY = "SELECT * FROM PASSENGER";
    static Connection connection = null;
     PreparedStatement ps=null;
      ResultSet  rs=null;
        public static String username = "";
     
                static String fname=null;
               static  String lname=null;
                static  int ID;
         

    /**
     * Creates new form PassengerMenu
     */
    public PassengerMenu() {
        initComponents();
        setData();
        setWelcome();
       
        
    }
    public void setData(){
        
        try{  connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");

                 ps = connection.prepareStatement("SELECT * FROM PASSENGER WHERE USERNAME =?");
           
             ps.setString(1, username);
                    rs = ps.executeQuery();
         
                  if(rs.next()){
               
                     fname=rs.getString("FNAME");
              lname=rs.getString("LNAME");
              ID=rs.getInt("ID_NUM");

                            
                      
              
                  }
              
                  


    }
    catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    public void setWelcome(){
        
        welcomeL.setText(fname+" "+lname);
        
    }
public void closeDB(){
    try{
 rs.close();
 ps.close();
 connection.close();
 
    }
    catch(SQLException ex){
        ex.printStackTrace();
    }
    
    
}
public boolean checkTicket(){
      boolean have=false;
      try{ 
        
          connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");

                 ps = connection.prepareStatement("SELECT * FROM TICKET WHERE PASSENGER_ID =?");
           
             ps.setString(1, String.valueOf(ID));
             
                    rs = ps.executeQuery();
         
                if(rs.next()){
         have=true;
         
                }
                else{
have=false;}
                
       


    }
    catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
  
       return have;
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        welcomeL = new javax.swing.JLabel();
        regestrationL2 = new javax.swing.JLabel();
        viewbookfBT = new javax.swing.JButton();
        bookfBT = new javax.swing.JButton();
        EditInfoBT = new javax.swing.JButton();
        cancelbookfBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeL.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        welcomeL.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(welcomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        regestrationL2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        regestrationL2.setForeground(new java.awt.Color(0, 0, 102));
        regestrationL2.setText("WELCOME");
        jPanel2.add(regestrationL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        viewbookfBT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewbookfBT.setForeground(new java.awt.Color(0, 0, 102));
        viewbookfBT.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/ticket.png")); // NOI18N
        viewbookfBT.setText("View My Tickets");
        viewbookfBT.setBorder(null);
        viewbookfBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewbookfBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewbookfBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbookfBTActionPerformed(evt);
            }
        });
        jPanel2.add(viewbookfBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 140, 140));

        bookfBT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookfBT.setForeground(new java.awt.Color(0, 0, 102));
        bookfBT.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/book.png")); // NOI18N
        bookfBT.setText("Book Flight ");
        bookfBT.setBorder(null);
        bookfBT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bookfBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bookfBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bookfBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookfBTActionPerformed(evt);
            }
        });
        jPanel2.add(bookfBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 140, -1));

        EditInfoBT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EditInfoBT.setForeground(new java.awt.Color(0, 0, 102));
        EditInfoBT.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/edit 2.png")); // NOI18N
        EditInfoBT.setText("Edit My Info");
        EditInfoBT.setBorder(null);
        EditInfoBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditInfoBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditInfoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInfoBTActionPerformed(evt);
            }
        });
        jPanel2.add(EditInfoBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 130));

        cancelbookfBT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelbookfBT.setForeground(new java.awt.Color(0, 0, 102));
        cancelbookfBT.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/cancel.png")); // NOI18N
        cancelbookfBT.setText("Cancel Booking");
        cancelbookfBT.setBorder(null);
        cancelbookfBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelbookfBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelbookfBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbookfBTActionPerformed(evt);
            }
        });
        jPanel2.add(cancelbookfBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 140, 140));

        logoutBT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logoutBT.setForeground(new java.awt.Color(0, 0, 102));
        logoutBT.setText("LOG OUT");
        logoutBT.setBorder(null);
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        jPanel2.add(logoutBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/backgroundPassengerMenu.jpg")); // NOI18N
        jPanel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewbookfBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbookfBTActionPerformed
if(checkTicket()){
    ViewT vticket = new ViewT();
    vticket.setVisible(true);
    dispose();
        
}
else{
                JOptionPane.showMessageDialog(null, "You Dont Have Any Reserved Tickets !");

}
        
  
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbookfBTActionPerformed

    private void EditInfoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInfoBTActionPerformed
      editinfo in=new editinfo();
      in.setVisible(true);
     
      dispose();
      setData();
          
        // TODO add your handling code here:
    }//GEN-LAST:event_EditInfoBTActionPerformed

    private void bookfBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookfBTActionPerformed

        // TODO add your handling code here:
            SearchingFlightsInterface s=   new SearchingFlightsInterface();
     s.setVisible(true);
     dispose();
     setData();
         
    }//GEN-LAST:event_bookfBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
closeDB();
        PassengerLoginForm p= new PassengerLoginForm();
p.setVisible(true);
dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBTActionPerformed

    private void cancelbookfBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbookfBTActionPerformed
if(checkTicket()){
    Cancelinterface ticket = new Cancelinterface();
    ticket.setVisible(true);
    dispose();
     
}
else{
                JOptionPane.showMessageDialog(null, "You Dont Have Any Reserved Tickets !");

}
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbookfBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditInfoBT;
    private javax.swing.JLabel background;
    private javax.swing.JButton bookfBT;
    private javax.swing.JButton cancelbookfBT;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBT;
    private javax.swing.JLabel regestrationL2;
    private javax.swing.JButton viewbookfBT;
    private javax.swing.JLabel welcomeL;
    // End of variables declaration//GEN-END:variables
}
