/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import static com.mycompany.airsea.Login.connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author shamsalotaibi
 */
public class PrintFlights extends javax.swing.JFrame {

    /**
     * Creates new form PrintFlights
     */
    public PrintFlights() {
        initComponents();
        tableH();
        pFlight();
    }
     public void tableH(){
        JTableHeader th=pf.getTableHeader();
        th.setForeground(Color.BLUE);
        th.setFont(new Font("Times New Roman",Font.BOLD,14));
        TableColumn tc1=pf.getColumnModel().getColumn(0);
        tc1.setPreferredWidth(100);
         TableColumn tc2=pf.getColumnModel().getColumn(1);
        tc2.setPreferredWidth(100);
         TableColumn tc3=pf.getColumnModel().getColumn(2);
        tc3.setPreferredWidth(100);
         TableColumn tc4=pf.getColumnModel().getColumn(3);
        tc4.setPreferredWidth(120);
         TableColumn tc5=pf.getColumnModel().getColumn(4);
        tc5.setPreferredWidth(120);
         TableColumn tc6=pf.getColumnModel().getColumn(5);
        tc6.setPreferredWidth(100);
         TableColumn tc7=pf.getColumnModel().getColumn(6);
        tc7.setPreferredWidth(100);
         TableColumn tc8=pf.getColumnModel().getColumn(7);
        tc8.setPreferredWidth(100);
         TableColumn tc9=pf.getColumnModel().getColumn(8);
        tc9.setPreferredWidth(100);
        
        
    }
    
    
   final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
    
    static Connection connection = null;
    
    
    String FlightNo=null;
    String FlightPrice=null;
    String Depdate=null;
    String Deptime=null;
    String Arridate=null;
           String Arritime=null;
              String Depcity=null;
           String airgno= null;
            String classt=null; 
            String Arricity;
            ResultSet rs=null;
            PreparedStatement ps=null;
    
    public void pFlight(){
        
           
       try {
             int rowC=0;
            connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
             ps = connection.prepareStatement("SELECT * FROM FLIGHT");
              
             
            rs=ps.executeQuery();
           while(rs.next()){
               
            FlightNo = String.valueOf(rs.getInt("FLIGHT_NO"));
            FlightPrice=String.valueOf(rs.getDouble("FLIGHT_PRICE"));
             Depdate=rs.getString("DEP_DATE");
            Deptime=rs.getString("DEP_TIME");
            Arridate=rs.getString("ARR_DATE");
           Arritime=rs.getString("ARR_TIME");
               Depcity=rs.getString("DEPARTURE_CITY");
                Arricity= rs.getString("ARRIVAL_CITY");  
               airgno= String.valueOf(rs.getInt("AIRPLANE_REGNO"));
             classt=rs.getString("CLASS"); 
             
             String data[]={FlightNo,Depdate,Deptime,Arridate,Arritime,Depcity,Arricity, airgno, classt,FlightPrice};
             DefaultTableModel tbM=(DefaultTableModel)pf.getModel();
        tbM.insertRow(rowC, data);

         
          
           
           
           
           
           
           }
           
           rs.close();
           ps.close();
           connection.close();
         
         
      
        
    }
       
        
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
        
        
        
        
        
    }
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pf = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("All The Available Flights Are Shown Below");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 450, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        pf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight no", "FlightPrice", "Dep Date", "Dep Time", "Arr Date", "Arr Time", "Dep City", "Arr City", "RGNO", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pf.setGridColor(new java.awt.Color(0, 51, 102));
        pf.setShowGrid(true);
        pf.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pfComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(pf);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 750, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/backgroundBig.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pfComponentAdded
        // TODO add your handling code here:
    
       
        
        
        
        
        
        
        
        
        
       
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_pfComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        AdminFunctions af= new  AdminFunctions();
        af.setVisible(true);
        dispose();
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintFlights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pf;
    // End of variables declaration//GEN-END:variables
}
