/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airsea;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author sadeem
 */
public class SearchingFlightsInterface extends javax.swing.JFrame {
   final String DATABASE_URL = "jdbc:derby://localhost:1527/AirSea";
    final String SELECT_QUERY = "SELECT * FROM FLIGHT";
     PreparedStatement ps=null;
      ResultSet rs=null;
     Connection connection = null;
     static public String depcity=null;
     static public String arricity=null;
    /**
     * Creates new form SearchingFlightsInterface
     */
    public SearchingFlightsInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        searchBt = new javax.swing.JButton();
        searchingL = new javax.swing.JLabel();
        cancelBt = new javax.swing.JButton();
        depcityL = new javax.swing.JLabel();
        arricityL = new javax.swing.JLabel();
        depCombo = new javax.swing.JComboBox<>();
        arriCombo = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBt.setBackground(new java.awt.Color(255, 255, 255));
        searchBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchBt.setForeground(new java.awt.Color(0, 0, 102));
        searchBt.setText("Search");
        searchBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtActionPerformed(evt);
            }
        });
        jPanel1.add(searchBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        searchingL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        searchingL.setForeground(new java.awt.Color(0, 0, 102));
        searchingL.setText("SEARCHING FOR FLIGHTS");
        jPanel1.add(searchingL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        cancelBt.setBackground(new java.awt.Color(255, 255, 255));
        cancelBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancelBt.setForeground(new java.awt.Color(0, 0, 102));
        cancelBt.setText("Cancel");
        cancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        depcityL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        depcityL.setForeground(new java.awt.Color(0, 0, 102));
        depcityL.setText("Departure City :");
        jPanel1.add(depcityL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        arricityL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        arricityL.setForeground(new java.awt.Color(0, 0, 102));
        arricityL.setText("Arrival City :");
        jPanel1.add(arricityL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        depCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        depCombo.setForeground(new java.awt.Color(0, 0, 102));
        depCombo.setMaximumRowCount(4);
        depCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Dammam", "Riyadh", "Jeddah", "Medina", "Al-Ahsa", "Al-'Ula", "Yanbu", "Buraidah" }));
        depCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depComboActionPerformed(evt);
            }
        });
        jPanel1.add(depCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        arriCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        arriCombo.setForeground(new java.awt.Color(0, 0, 102));
        arriCombo.setMaximumRowCount(4);
        arriCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Dammam", "Riyadh", "Jeddah", "Medina", "Al-Ahsa", "Al-'Ula", "Yanbu", "Buraidah" }));
        jPanel1.add(arriCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("/Users/sadeem/NetBeansProjects/AIRSEA/src/pics/background1.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depComboActionPerformed

    private void searchBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtActionPerformed
        // TODO add your handling code here:
        try {
            connection = DriverManager.getConnection(DATABASE_URL, "Sadeem", "123");
            ps = connection.prepareStatement("SELECT * FROM FLIGHT WHERE DEPARTURE_CITY =? AND ARRIVAL_CITY =?");

            depcity= depCombo.getSelectedItem().toString();
            arricity = arriCombo.getSelectedItem().toString();

            ps.setString(1, depcity);
            ps.setString(2, arricity);
            rs = ps.executeQuery();
            if(depcity!= " "&& arricity!= " "){
                if (rs.next()) {

                    availableFlights p=   new availableFlights();
                    p.setVisible(true);
                    dispose();
                    closeDB();

                } else {
                    String mess="Sorry We Dont have Flights from "+depcity+" to "+arricity;
                    JOptionPane.showMessageDialog(null, mess , "Error", ERROR_MESSAGE);
                }}else
                {
                    String mess="Please Select Both Departure City and Arrival City ";
                    JOptionPane.showMessageDialog(null, mess , "Error", ERROR_MESSAGE);
                }

            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_searchBtActionPerformed

    private void cancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtActionPerformed
        PassengerMenu p=new PassengerMenu();
        p.setVisible(true);
        dispose();
        closeDB();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtActionPerformed
 public void closeDB(){
        try{
        rs.close();
        ps.close();
        connection.close();}
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchingFlightsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchingFlightsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchingFlightsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchingFlightsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchingFlightsInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> arriCombo;
    private javax.swing.JLabel arricityL;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelBt;
    private javax.swing.ButtonGroup classBG;
    private javax.swing.JComboBox<String> depCombo;
    private javax.swing.JLabel depcityL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchBt;
    private javax.swing.JLabel searchingL;
    // End of variables declaration//GEN-END:variables
}
